import esbuild from "esbuild";
import { execFile } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import process from "process";
import { promisify } from "node:util";
import builtins from "builtin-modules";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const pluginId = "side-note2";
const hotReloadEnabled = !prod && process.env.SIDENOTE2_HOT_RELOAD !== "0";
const execFileAsync = promisify(execFile);

let hotReloadInFlight = false;
let hotReloadQueued = false;

async function reloadPlugin() {
	if (!hotReloadEnabled) {
		return;
	}

	if (hotReloadInFlight) {
		hotReloadQueued = true;
		return;
	}

	hotReloadInFlight = true;

	do {
		hotReloadQueued = false;
		try {
			await execFileAsync("obsidian", ["plugin:reload", `id=${pluginId}`]);
			console.log(`[hot-reload] Reloaded ${pluginId}`);
		} catch (error) {
			const message =
				error instanceof Error
					? error.message
					: String(error);
			console.warn(`[hot-reload] Failed to reload ${pluginId}: ${message}`);
		}
	} while (hotReloadQueued);

	hotReloadInFlight = false;
}

function assertNoProdSourceMapArtifacts() {
	const mainJsPath = "main.js";
	const mainJs = readFileSync(mainJsPath, "utf8");
	if (mainJs.includes("sourceMappingURL") || mainJs.includes("sourcesContent")) {
		throw new Error(`Production build leaked source map markers into ${mainJsPath}`);
	}

	const rootSourceMapPath = "main.js.map";
	if (existsSync(rootSourceMapPath)) {
		throw new Error(`Production build emitted unexpected source map ${rootSourceMapPath}`);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	define: {
		__DEV__: JSON.stringify(!prod),
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	loader: {
		".md": "text",
	},
	minify: prod,
	plugins: prod
		? []
		: [
			{
				name: "obsidian-hot-reload",
				setup(build) {
					build.onEnd(async (result) => {
						if (result.errors.length > 0) {
							return;
						}

						await reloadPlugin();
					});
				},
			},
		],
});

if (prod) {
	await context.rebuild();
	assertNoProdSourceMapArtifacts();
	process.exit(0);
} else {
	await context.watch();
}
