import * as assert from "node:assert/strict";
import test from "node:test";
import {
    ALL_COMMENTS_NOTE_PATH,
    ALL_COMMENTS_NOTE_IMAGE_ALT,
    ALL_COMMENTS_NOTE_IMAGE_CAPTION,
    ALL_COMMENTS_NOTE_IMAGE_URL,
    buildAllCommentsNoteContent,
    buildCommentLocationUrl,
    findCommentLocationTargetInMarkdownLine,
    isAllCommentsNotePath,
    LEGACY_ALL_COMMENTS_NOTE_PATH,
    normalizeAllCommentsNoteImageCaption,
    normalizeAllCommentsNoteImageUrl,
    normalizeAllCommentsNotePath,
    parseCommentLocationUrl,
} from "../src/core/derived/allCommentsNote";
import type { Comment } from "../src/commentManager";

function createComment(overrides: Partial<Comment> = {}): Comment {
    return {
        id: "comment-1",
        filePath: "Folder/Note.md",
        startLine: 4,
        startChar: 2,
        endLine: 4,
        endChar: 7,
        selectedText: "hello",
        selectedTextHash: "hash-1",
        comment: "This is a side note.",
        timestamp: 1710000000000,
        resolved: false,
        ...overrides,
    };
}

test("buildCommentLocationUrl encodes vault, file, and comment id", () => {
    const url = buildCommentLocationUrl("dev vault", createComment({
        filePath: "Folder/My Note.md",
        id: "comment 1",
    }));

    assert.equal(
        url,
        "obsidian://side-note2-comment?vault=dev%20vault&file=Folder%2FMy%20Note.md&commentId=comment%201"
    );
});

test("parseCommentLocationUrl extracts file path and comment id", () => {
    assert.deepEqual(
        parseCommentLocationUrl("obsidian://side-note2-comment?vault=dev&file=Folder%2FMy%20Note.md&commentId=comment%201"),
        {
            filePath: "Folder/My Note.md",
            commentId: "comment 1",
        },
    );
    assert.equal(parseCommentLocationUrl("obsidian://open?vault=dev&file=Folder%2FMy%20Note.md"), null);
});

test("findCommentLocationTargetInMarkdownLine finds the side note target in a generated markdown list row", () => {
    assert.deepEqual(
        findCommentLocationTargetInMarkdownLine('<span class="sidenote2-index-kind-dot sidenote2-index-kind-page"></span> [hello](obsidian://side-note2-comment?vault=dev&file=Folder%2FNote.md&commentId=comment-1&kind=page)  #hi'),
        {
            filePath: "Folder/Note.md",
            commentId: "comment-1",
        },
    );
    assert.equal(findCommentLocationTargetInMarkdownLine("**Folder/Note.md**"), null);
});

test("buildAllCommentsNoteContent groups comments by file and shows selected text and comment", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            filePath: "B.md",
            selectedText: "beta",
            comment: "Comment B",
            startLine: 8,
        }),
        createComment({
            id: "comment-2",
            filePath: "A.md",
            selectedText: "alpha",
            comment: "Comment A",
            startLine: 2,
            resolved: true,
        }),
    ]);

    assert.match(content, new RegExp(`!\\[${ALL_COMMENTS_NOTE_IMAGE_ALT.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\]\\(${ALL_COMMENTS_NOTE_IMAGE_URL.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\)`));
    assert.match(content, new RegExp(`<div class="sidenote2-index-header-caption">${ALL_COMMENTS_NOTE_IMAGE_CAPTION.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}</div>`));
    assert.doesNotMatch(content, /# Side comments/);
    assert.doesNotMatch(content, /Generated by SideNote2/);
    assert.doesNotMatch(content, /Total comments:/);
    assert.doesNotMatch(content, /## Connected Notes/);
    assert.doesNotMatch(content, /Page notes/);
    assert.doesNotMatch(content, /Anchored notes/);
    assert.match(content, /<strong class="sidenote2-index-heading-label">A\.md<\/strong>[\s\S]*<span class="sidenote2-index-kind-dot sidenote2-index-kind-anchored"><\/span> \[~~alpha~~\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=A\.md&commentId=comment-2&kind=anchored\)/);
    assert.match(content, /<strong class="sidenote2-index-heading-label">B\.md<\/strong>[\s\S]*<span class="sidenote2-index-kind-dot sidenote2-index-kind-anchored"><\/span> \[beta\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=B\.md&commentId=comment-1&kind=anchored\)/);
    assert.doesNotMatch(content, /Comment A/);
    assert.doesNotMatch(content, /\[\[[^\]]+\]\]/);
    assert.doesNotMatch(content, /sidenote2-index-heading-link/);
    assert.ok(content.indexOf('<strong class="sidenote2-index-heading-label">A.md</strong>') < content.indexOf('<strong class="sidenote2-index-heading-label">B.md</strong>'));
});

test("buildAllCommentsNoteContent renders an empty file when there are no comments", () => {
    const content = buildAllCommentsNoteContent("dev", []);

    assert.equal(
        content,
        `![${ALL_COMMENTS_NOTE_IMAGE_ALT}](${ALL_COMMENTS_NOTE_IMAGE_URL})\n<div class="sidenote2-index-header-caption">${ALL_COMMENTS_NOTE_IMAGE_CAPTION}</div>\n`,
    );
});

test("buildAllCommentsNoteContent uses a custom header image URL when provided", () => {
    const customImageUrl = "https://example.com/relativity.webp";
    const customCaption = "Custom caption";
    const content = buildAllCommentsNoteContent("dev", [], {
        headerImageUrl: customImageUrl,
        headerImageCaption: customCaption,
    });

    assert.equal(
        content,
        `![${ALL_COMMENTS_NOTE_IMAGE_ALT}](${customImageUrl})\n<div class="sidenote2-index-header-caption">${customCaption}</div>\n`,
    );
});

test("buildAllCommentsNoteContent omits the figcaption when the custom caption is blank", () => {
    const content = buildAllCommentsNoteContent("dev", [], {
        headerImageCaption: "",
    });

    assert.equal(
        content,
        `![${ALL_COMMENTS_NOTE_IMAGE_ALT}](${ALL_COMMENTS_NOTE_IMAGE_URL})\n`,
    );
});

test("buildAllCommentsNoteContent ignores comments attached to the generated aggregate note", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            filePath: ALL_COMMENTS_NOTE_PATH,
            selectedText: "self",
        }),
        createComment({
            id: "comment-2",
            filePath: "Z.md",
            selectedText: "real",
        }),
    ]);

    assert.doesNotMatch(content, /\[\[SideNote2 comments\.md\]\]/);
    assert.match(content, /<strong class="sidenote2-index-heading-label">Z\.md<\/strong>/);
});

test("buildAllCommentsNoteContent escapes markdown-heavy selections and truncates long previews", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            selectedText: "Use `/path/to/SideNote2`, `[Vault]`, and `<tag>` placeholders instead of machine-local paths in docs.",
        }),
    ]);

    assert.match(content, /\[Use \\`\/path\/to\/SideNote2\\`, \\`\\\[Vault\\\]\\`, and \\`\\<tag\\>\\` placeholders instead of mach\.\.\.\]/);
});

test("buildAllCommentsNoteContent includes extracted comment tags for search", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            comment: "Track this with #hi and #follow/up next.",
        }),
    ]);

    assert.match(content, /<span class="sidenote2-index-kind-dot sidenote2-index-kind-anchored"><\/span> \[hello\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=comment-1&kind=anchored\)  #hi #follow\/up/);
});

test("buildAllCommentsNoteContent labels page notes and orphaned notes", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            id: "page-note",
            anchorKind: "page",
            selectedText: "Note",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
        }),
        createComment({
            id: "orphan-note",
            orphaned: true,
            selectedText: "missing text",
            startLine: 10,
        }),
    ]);

    assert.equal(content.match(/<strong class="sidenote2-index-heading-label">Folder\/Note\.md<\/strong>/g)?.length ?? 0, 1);
    assert.match(content, /<strong class="sidenote2-index-heading-label">Folder\/Note\.md<\/strong>[\s\S]*<span class="sidenote2-index-kind-dot sidenote2-index-kind-page"><\/span> \[pn1\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note&kind=page\)\n<span class="sidenote2-index-kind-dot sidenote2-index-kind-anchored"><\/span> \[orphaned · missing text\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=orphan-note&kind=anchored\)/);
});

test("buildAllCommentsNoteContent numbers page notes per file when no mentioned page label is available", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            id: "page-note-1",
            filePath: "Folder/Note.md",
            anchorKind: "page",
            selectedText: "Note",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
            timestamp: 1,
        }),
        createComment({
            id: "page-note-2",
            filePath: "Folder/Note.md",
            anchorKind: "page",
            selectedText: "Note",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
            timestamp: 2,
        }),
        createComment({
            id: "page-note-other-file",
            filePath: "Folder/Other.md",
            anchorKind: "page",
            selectedText: "Other",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
            timestamp: 3,
        }),
    ]);

    assert.match(content, /<strong class="sidenote2-index-heading-label">Folder\/Note\.md<\/strong>[\s\S]*\[pn1\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note-1&kind=page\)/);
    assert.match(content, /<strong class="sidenote2-index-heading-label">Folder\/Note\.md<\/strong>[\s\S]*\[pn2\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note-2&kind=page\)/);
    assert.match(content, /<strong class="sidenote2-index-heading-label">Folder\/Other\.md<\/strong>[\s\S]*\[pn1\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FOther\.md&commentId=page-note-other-file&kind=page\)/);
});

test("buildAllCommentsNoteContent keeps page note rows clean and expands anchored mentioned pages", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            id: "page-note",
            anchorKind: "page",
            selectedText: "Folder/Note",
            comment: "See [[Another page]] and [[Another page|Alias]] plus [[Third page]].",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
        }),
        createComment({
            id: "anchored-note",
            selectedText: "hello",
            comment: "Track [[Roadmap]] for this",
            startLine: 4,
        }),
    ], {
        getMentionedPageLabels: (comment) => {
            if (comment.id === "page-note") {
                return ["Another page", "Another page", "Third page"];
            }

            if (comment.id === "anchored-note") {
                return ["Roadmap"];
            }

            return [];
        },
        resolveWikiLinkPath: (linkPath) => `${linkPath}.md`,
    });

    assert.match(content, /<span class="sidenote2-index-kind-dot sidenote2-index-kind-page"><\/span> \[pn1\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note&kind=page\)/);
    assert.equal(
        content.match(/\[pn1\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note&kind=page\)/g)?.length ?? 0,
        1,
    );
    assert.match(content, /<span class="sidenote2-index-kind-dot sidenote2-index-kind-anchored"><\/span> \[hello · Roadmap\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=anchored-note&kind=anchored\)/);
    assert.doesNotMatch(content, />Another page<\/a>/);
    assert.doesNotMatch(content, />Third page<\/a>/);
    assert.match(content, /-> <a class="external-link sidenote2-index-target-link" href="obsidian:\/\/open\?vault=dev&amp;file=Roadmap\.md" target="_blank" rel="noopener nofollow">Roadmap<\/a>/);
});

test("isAllCommentsNotePath matches the generated note path", () => {
    assert.equal(isAllCommentsNotePath(ALL_COMMENTS_NOTE_PATH), true);
    assert.equal(isAllCommentsNotePath(LEGACY_ALL_COMMENTS_NOTE_PATH), true);
    assert.equal(isAllCommentsNotePath("notes/custom index.md", "notes/custom index.md"), true);
    assert.equal(isAllCommentsNotePath("Random.md"), false);
});

test("normalizeAllCommentsNotePath keeps the default and adds md when needed", () => {
    assert.equal(normalizeAllCommentsNotePath(""), ALL_COMMENTS_NOTE_PATH);
    assert.equal(normalizeAllCommentsNotePath("notes/custom index"), "notes/custom index.md");
    assert.equal(normalizeAllCommentsNotePath("notes/custom index.md"), "notes/custom index.md");
});

test("normalizeAllCommentsNoteImageUrl keeps the default when blank", () => {
    assert.equal(normalizeAllCommentsNoteImageUrl(""), ALL_COMMENTS_NOTE_IMAGE_URL);
    assert.equal(normalizeAllCommentsNoteImageUrl(" https://example.com/header.webp "), "https://example.com/header.webp");
});

test("normalizeAllCommentsNoteImageCaption keeps the default when missing and allows blank", () => {
    assert.equal(normalizeAllCommentsNoteImageCaption(null), ALL_COMMENTS_NOTE_IMAGE_CAPTION);
    assert.equal(normalizeAllCommentsNoteImageCaption(" Custom caption "), "Custom caption");
    assert.equal(normalizeAllCommentsNoteImageCaption(" "), "");
});
