export function renderPrivatePublishShellHtml(): string {
	return [
		"<!doctype html>",
		"<html lang=\"en\">",
		"<head>",
		"\t<meta charset=\"utf-8\">",
		"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
		"\t<title>Published Aside Wiki</title>",
		"\t<link rel=\"stylesheet\" href=\"/_aside/styles.css\">",
		"</head>",
		"<body>",
		"\t<div id=\"aside-private-publish-app\">",
		"\t\t<div class=\"aside-publish-loading\">Loading published wiki...</div>",
		"\t</div>",
		"\t<script type=\"module\" src=\"/_aside/app.js\"></script>",
		"</body>",
		"</html>",
		"",
	].join("\n");
}

export function renderPrivatePublishShellScript(): string {
	return [
		"const manifestEndpoint = \"/_aside/api/site-manifest\";",
		"const commentsEndpoint = \"/_aside/api/comments\";",
		"const request = globalThis[\"fet\" + \"ch\"].bind(globalThis);",
		"const state = { manifest: null, selectedPath: new URLSearchParams(location.search).get(\"path\") || \"\", comments: [], notice: \"\" };",
		"const root = document.getElementById(\"aside-private-publish-app\");",
		"",
		"async function loadManifest() {",
		"\tconst response = await request(manifestEndpoint, { credentials: \"include\" });",
		"\tif (!response.ok) {",
		"\t\tthrow new Error(\"Unable to load the published site manifest.\");",
		"\t}",
		"\tstate.manifest = await response.json();",
		"\tconst files = Array.isArray(state.manifest.files) ? state.manifest.files : [];",
		"\tif (!files.some((file) => file.publicPath === state.selectedPath)) {",
		"\t\tstate.selectedPath = files[0]?.publicPath || \"\";",
		"\t}",
		"}",
		"",
		"async function loadComments() {",
		"\tif (!state.selectedPath) {",
		"\t\tstate.comments = [];",
		"\t\treturn;",
		"\t}",
		"\ttry {",
		"\t\tconst response = await request(`${commentsEndpoint}?path=${encodeURIComponent(state.selectedPath)}`, { credentials: \"include\" });",
		"\t\tconst payload = response.ok ? await response.json() : { comments: [] };",
		"\t\tstate.comments = Array.isArray(payload.comments) ? payload.comments : [];",
		"\t} catch {",
		"\t\tstate.comments = [];",
		"\t}",
		"}",
		"",
		"function getSelectedFile() {",
		"\tconst files = Array.isArray(state.manifest?.files) ? state.manifest.files : [];",
		"\treturn files.find((file) => file.publicPath === state.selectedPath) || null;",
		"}",
		"",
		"function setSelectedPath(path) {",
		"\tstate.selectedPath = path;",
		"\tconst url = new URL(location.href);",
		"\turl.searchParams.set(\"path\", path);",
		"\thistory.replaceState(null, \"\", url);",
		"\tvoid refreshCommentsAndRender();",
		"}",
		"",
		"async function refreshCommentsAndRender() {",
		"\tawait loadComments();",
		"\trender();",
		"}",
		"",
		"function createElement(tag, options = {}, children = []) {",
		"\tconst element = document.createElement(tag);",
		"\tif (options.className) {",
		"\t\telement.className = options.className;",
		"\t}",
		"\tif (options.text !== undefined) {",
		"\t\telement.textContent = options.text;",
		"\t}",
		"\tif (options.href) {",
		"\t\telement.href = options.href;",
		"\t}",
		"\tif (options.type) {",
		"\t\telement.type = options.type;",
		"\t}",
		"\tif (options.value !== undefined) {",
		"\t\telement.value = options.value;",
		"\t}",
		"\tif (options.disabled) {",
		"\t\telement.disabled = true;",
		"\t}",
		"\tfor (const child of children) {",
		"\t\telement.append(child);",
		"\t}",
		"\treturn element;",
		"}",
		"",
		"function renderTreeNode(node) {",
		"\tif (node.type === \"file\") {",
		"\t\tconst button = createElement(\"button\", {",
		"\t\t\tclassName: `aside-publish-tree-file${node.path === state.selectedPath ? \" is-selected\" : \"\"}`,",
		"\t\t\ttext: node.name,",
		"\t\t\ttype: \"button\",",
		"\t\t});",
		"\t\tbutton.addEventListener(\"click\", () => setSelectedPath(node.path));",
		"\t\treturn createElement(\"li\", {}, [button]);",
		"\t}",
		"\tconst childList = createElement(\"ul\", {}, (Array.isArray(node.children) ? node.children : []).map(renderTreeNode));",
		"\treturn createElement(\"li\", { className: \"aside-publish-tree-folder\" }, [",
		"\t\tcreateElement(\"div\", { className: \"aside-publish-folder-label\", text: node.name || \"Published\" }),",
		"\t\tchildList,",
		"\t]);",
		"}",
		"",
		"function renderTree() {",
		"\tconst tree = state.manifest?.tree;",
		"\tconst nodes = tree ? (Array.isArray(tree.children) ? tree.children : []).map(renderTreeNode) : [];",
		"\treturn createElement(\"nav\", { className: \"aside-publish-tree\", text: \"\" }, [",
		"\t\tcreateElement(\"div\", { className: \"aside-publish-panel-title\", text: \"Files\" }),",
		"\t\tcreateElement(\"ul\", {}, nodes),",
		"\t]);",
		"}",
		"",
		"function renderAuth() {",
		"\tconst identity = state.manifest?.identity;",
		"\tif (identity) {",
		"\t\tconst label = identity.name || identity.identifier;",
		"\t\treturn createElement(\"form\", { className: \"aside-publish-auth\", text: \"\" }, [",
		"\t\t\tcreateElement(\"span\", { text: label }),",
		"\t\t\tcreateElement(\"button\", { type: \"submit\", text: \"Sign out\" }),",
		"\t\t]);",
		"\t}",
		"\treturn createElement(\"a\", { className: \"aside-publish-login\", href: \"/_aside/api/auth/google/start\", text: \"Sign in with Google\" });",
		"}",
		"",
		"function renderViewer() {",
		"\tconst file = getSelectedFile();",
		"\tif (!file) {",
		"\t\treturn createElement(\"main\", { className: \"aside-publish-viewer\" }, [",
		"\t\t\tcreateElement(\"div\", { className: \"aside-publish-empty\", text: \"No files are available for this account.\" }),",
		"\t\t]);",
		"\t}",
		"\tconst versions = Array.isArray(file.versions) ? file.versions : [];",
		"\tconst currentVersion = file.currentVersion || versions[0] || {};",
		"\tconst versionSelect = createElement(\"select\", { className: \"aside-publish-version\" }, versions.map((version) =>",
		"\t\tcreateElement(\"option\", { value: version.id, text: new Date(version.publishedAt).toLocaleString() })));",
		"\tconst frame = createElement(\"iframe\", { className: \"aside-publish-frame\" });",
		"\tframe.src = file.routePath;",
		"\tframe.title = file.publicPath;",
		"\treturn createElement(\"main\", { className: \"aside-publish-viewer\" }, [",
		"\t\tcreateElement(\"header\", { className: \"aside-publish-viewer-header\" }, [",
		"\t\t\tcreateElement(\"div\", {}, [",
		"\t\t\t\tcreateElement(\"div\", { className: \"aside-publish-path\", text: file.publicPath }),",
		"\t\t\t\tcreateElement(\"h1\", { text: file.publicPath.split(\"/\").pop() || file.publicPath }),",
		"\t\t\t\tcreateElement(\"div\", { className: \"aside-publish-version-note\", text: currentVersion.contentHash || \"Current version\" }),",
		"\t\t\t]),",
		"\t\t\tcreateElement(\"label\", { className: \"aside-publish-version-label\" }, [",
		"\t\t\t\tcreateElement(\"span\", { text: \"Version\" }),",
		"\t\t\t\tversionSelect,",
		"\t\t\t]),",
		"\t\t]),",
		"\t\tframe,",
		"\t]);",
		"}",
		"",
		"async function submitComment(event) {",
		"\tevent.preventDefault();",
		"\tconst form = event.currentTarget;",
		"\tconst body = new FormData(form).get(\"body\");",
		"\tif (typeof body !== \"string\" || !body.trim()) {",
		"\t\treturn;",
		"\t}",
		"\tconst parentId = form.dataset.parentId || \"\";",
		"\tconst payload = parentId",
		"\t\t? { op: \"appendReply\", path: state.selectedPath, parentId, body: body.trim() }",
		"\t\t: { path: state.selectedPath, body: body.trim() };",
		"\tconst response = await request(commentsEndpoint, {",
		"\t\tmethod: \"POST\",",
		"\t\tcredentials: \"include\",",
		"\t\theaders: { \"Content-Type\": \"application/json\" },",
		"\t\tbody: JSON.stringify(payload),",
		"\t});",
		"\tstate.notice = response.ok ? (parentId ? \"Reply added.\" : \"Comment added.\") : \"Comments are not available yet.\";",
		"\tawait refreshCommentsAndRender();",
		"}",
		"",
		"function renderComment(comment, canComment) {",
		"\tconst replies = (Array.isArray(comment.replies) ? comment.replies : []).map((reply) => renderComment(reply, false));",
		"\tconst children = [",
		"\t\tcreateElement(\"div\", { className: \"aside-publish-comment-author\", text: comment.author?.displayName || comment.author?.identity || \"Viewer\" }),",
		"\t\tcreateElement(\"p\", { text: comment.body || \"\" }),",
		"\t];",
		"\tif (replies.length > 0) {",
		"\t\tchildren.push(createElement(\"div\", { className: \"aside-publish-comment-replies\" }, replies));",
		"\t}",
		"\tif (canComment) {",
		"\t\tconst replyForm = createElement(\"form\", { className: \"aside-publish-comment-form aside-publish-reply-form\" }, [",
		"\t\t\tcreateElement(\"textarea\", { text: \"\" }),",
		"\t\t\tcreateElement(\"button\", { type: \"submit\", text: \"Reply\" }),",
		"\t\t]);",
		"\t\treplyForm.dataset.parentId = comment.id || \"\";",
		"\t\treplyForm.querySelector(\"textarea\").name = \"body\";",
		"\t\treplyForm.addEventListener(\"submit\", submitComment);",
		"\t\tchildren.push(replyForm);",
		"\t}",
		"\treturn createElement(\"article\", { className: \"aside-publish-comment\" }, children);",
		"}",
		"",
		"function renderSidebar() {",
		"\tconst file = getSelectedFile();",
		"\tconst canComment = Boolean(file?.permission?.canComment);",
		"\tconst comments = state.comments.map((comment) => renderComment(comment, canComment));",
		"\tconst form = createElement(\"form\", { className: \"aside-publish-comment-form\" }, [",
		"\t\tcreateElement(\"textarea\", { text: \"\", disabled: !canComment }),",
		"\t\tcreateElement(\"button\", { type: \"submit\", text: \"Add comment\", disabled: !canComment }),",
		"\t]);",
		"\tform.querySelector(\"textarea\").name = \"body\";",
		"\tform.addEventListener(\"submit\", submitComment);",
		"\treturn createElement(\"aside\", { className: \"aside-publish-sidebar\" }, [",
		"\t\tcreateElement(\"div\", { className: \"aside-publish-panel-title\", text: \"Aside\" }),",
		"\t\t...comments,",
		"\t\tcomments.length === 0 ? createElement(\"div\", { className: \"aside-publish-empty\", text: \"No comments yet.\" }) : document.createTextNode(\"\"),",
		"\t\tstate.notice ? createElement(\"div\", { className: \"aside-publish-notice\", text: state.notice }) : document.createTextNode(\"\"),",
		"\t\tform,",
		"\t]);",
		"}",
		"",
		"function render() {",
		"\troot.replaceChildren(createElement(\"div\", { className: \"aside-publish-shell\" }, [",
		"\t\tcreateElement(\"section\", { className: \"aside-publish-left\" }, [renderTree()]),",
		"\t\trenderViewer(),",
		"\t\trenderSidebar(),",
		"\t\tcreateElement(\"section\", { className: \"aside-publish-account\" }, [renderAuth()]),",
		"\t]));",
		"\troot.querySelector(\".aside-publish-auth\")?.addEventListener(\"submit\", async (event) => {",
		"\t\tevent.preventDefault();",
		"\t\tawait request(\"/_aside/api/auth/logout\", { method: \"POST\", credentials: \"include\" });",
		"\t\tlocation.reload();",
		"\t});",
		"}",
		"",
		"async function boot() {",
		"\ttry {",
		"\t\tawait loadManifest();",
		"\t\tawait loadComments();",
		"\t\trender();",
		"\t} catch (error) {",
		"\t\troot.replaceChildren(createElement(\"div\", { className: \"aside-publish-error\", text: error.message || \"Unable to load this published wiki.\" }));",
		"\t}",
		"}",
		"",
		"void boot();",
		"",
	].join("\n");
}

export function renderPrivatePublishShellStyles(): string {
	return [
		":root {",
		"\tcolor-scheme: light;",
		"\t--aside-shell-bg: #f7f8f4;",
		"\t--aside-shell-panel: #ffffff;",
		"\t--aside-shell-line: #d7ddd2;",
		"\t--aside-shell-text: #1c211b;",
		"\t--aside-shell-muted: #697268;",
		"\t--aside-shell-accent: #0f766e;",
		"\t--aside-shell-accent-strong: #134e4a;",
		"\t--aside-shell-warm: #b45309;",
		"}",
		"",
		"* { box-sizing: border-box; }",
		"body {",
		"\tmargin: 0;",
		"\tbackground: var(--aside-shell-bg);",
		"\tcolor: var(--aside-shell-text);",
		"\tfont-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
		"}",
		"",
		"button, select, textarea { font: inherit; }",
		"button, .aside-publish-login {",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 6px;",
		"\tbackground: var(--aside-shell-panel);",
		"\tcolor: var(--aside-shell-text);",
		"\tcursor: pointer;",
		"}",
		"button:hover, .aside-publish-login:hover { border-color: var(--aside-shell-accent); }",
		"button:disabled, textarea:disabled { cursor: not-allowed; opacity: 0.55; }",
		"",
		".aside-publish-shell {",
		"\tmin-height: 100vh;",
		"\tdisplay: grid;",
		"\tgrid-template-columns: minmax(220px, 280px) minmax(0, 1fr) minmax(260px, 340px);",
		"\tgrid-template-rows: auto 1fr;",
		"\tbackground: linear-gradient(90deg, #eef3ed 0, #f7f8f4 22%, #f7f8f4 78%, #f3f0e8 100%);",
		"}",
		".aside-publish-left, .aside-publish-sidebar {",
		"\tmin-height: 100vh;",
		"\tpadding: 18px;",
		"\tbackground: color-mix(in srgb, var(--aside-shell-panel) 86%, transparent);",
		"}",
		".aside-publish-left { border-right: 1px solid var(--aside-shell-line); }",
		".aside-publish-sidebar { border-left: 1px solid var(--aside-shell-line); }",
		".aside-publish-account {",
		"\tposition: fixed;",
		"\ttop: 14px;",
		"\tright: 18px;",
		"\tz-index: 2;",
		"}",
		".aside-publish-auth, .aside-publish-login {",
		"\tdisplay: flex;",
		"\tgap: 8px;",
		"\talign-items: center;",
		"\tpadding: 7px 9px;",
		"\ttext-decoration: none;",
		"\tbox-shadow: 0 8px 24px rgba(20, 45, 36, 0.08);",
		"}",
		".aside-publish-panel-title {",
		"\tmargin-bottom: 12px;",
		"\tcolor: var(--aside-shell-muted);",
		"\tfont-size: 12px;",
		"\tfont-weight: 700;",
		"\tletter-spacing: 0;",
		"\ttext-transform: uppercase;",
		"}",
		".aside-publish-tree ul {",
		"\tlist-style: none;",
		"\tmargin: 0;",
		"\tpadding: 0 0 0 12px;",
		"}",
		".aside-publish-tree > ul { padding-left: 0; }",
		".aside-publish-folder-label {",
		"\tmargin: 10px 0 5px;",
		"\tcolor: var(--aside-shell-muted);",
		"\tfont-size: 13px;",
		"}",
		".aside-publish-tree-file {",
		"\twidth: 100%;",
		"\tmin-height: 32px;",
		"\tmargin: 2px 0;",
		"\tpadding: 6px 8px;",
		"\ttext-align: left;",
		"\tbackground: transparent;",
		"\tborder-color: transparent;",
		"}",
		".aside-publish-tree-file.is-selected {",
		"\tbackground: #dcebe6;",
		"\tborder-color: #9ac7bd;",
		"\tcolor: var(--aside-shell-accent-strong);",
		"}",
		".aside-publish-viewer {",
		"\tmin-width: 0;",
		"\tpadding: 20px 22px 28px;",
		"\tdisplay: flex;",
		"\tflex-direction: column;",
		"\tgap: 14px;",
		"}",
		".aside-publish-viewer-header {",
		"\tdisplay: flex;",
		"\tjustify-content: space-between;",
		"\tgap: 16px;",
		"\talign-items: end;",
		"\tpadding-right: 168px;",
		"}",
		".aside-publish-path {",
		"\tcolor: var(--aside-shell-muted);",
		"\tfont-size: 12px;",
		"}",
		".aside-publish-version-note {",
		"\tmargin-top: 5px;",
		"\tcolor: var(--aside-shell-muted);",
		"\tfont-family: ui-monospace, \"SFMono-Regular\", Consolas, monospace;",
		"\tfont-size: 11px;",
		"}",
		".aside-publish-viewer h1 {",
		"\tmargin: 3px 0 0;",
		"\tfont-size: 24px;",
		"\tline-height: 1.2;",
		"\tletter-spacing: 0;",
		"}",
		".aside-publish-version-label {",
		"\tdisplay: grid;",
		"\tgap: 4px;",
		"\tcolor: var(--aside-shell-muted);",
		"\tfont-size: 12px;",
		"}",
		".aside-publish-version {",
		"\tmax-width: 220px;",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 6px;",
		"\tpadding: 6px 8px;",
		"}",
		".aside-publish-frame {",
		"\twidth: 100%;",
		"\tmin-height: 72vh;",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 8px;",
		"\tbackground: white;",
		"\tbox-shadow: 0 18px 46px rgba(35, 55, 43, 0.1);",
		"}",
		".aside-publish-comment {",
		"\tmargin-bottom: 12px;",
		"\tpadding: 10px;",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 8px;",
		"\tbackground: #fbfcfa;",
		"}",
		".aside-publish-comment-author {",
		"\tmargin-bottom: 5px;",
		"\tcolor: var(--aside-shell-accent-strong);",
		"\tfont-size: 12px;",
		"\tfont-weight: 700;",
		"}",
		".aside-publish-comment p { margin: 0; line-height: 1.45; }",
		".aside-publish-comment-replies {",
		"\tmargin-top: 10px;",
		"\tpadding-left: 10px;",
		"\tborder-left: 2px solid #c6d9d3;",
		"}",
		".aside-publish-comment-replies .aside-publish-comment {",
		"\tmargin-bottom: 8px;",
		"\tpadding: 8px;",
		"\tbackground: #f5f8f6;",
		"}",
		".aside-publish-comment-form { display: grid; gap: 8px; margin-top: 14px; }",
		".aside-publish-comment-form textarea {",
		"\twidth: 100%;",
		"\tmin-height: 96px;",
		"\tresize: vertical;",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 8px;",
		"\tpadding: 9px;",
		"}",
		".aside-publish-reply-form { margin-top: 10px; }",
		".aside-publish-reply-form textarea { min-height: 64px; }",
		".aside-publish-comment-form button { min-height: 34px; color: var(--aside-shell-accent-strong); }",
		".aside-publish-empty, .aside-publish-loading, .aside-publish-error, .aside-publish-notice {",
		"\tpadding: 12px;",
		"\tborder: 1px solid var(--aside-shell-line);",
		"\tborder-radius: 8px;",
		"\tbackground: #fbfcfa;",
		"\tcolor: var(--aside-shell-muted);",
		"}",
		".aside-publish-notice { color: var(--aside-shell-warm); }",
		"",
		"@media (max-width: 860px) {",
		"\t.aside-publish-shell {",
		"\t\tgrid-template-columns: 1fr;",
		"\t\tgrid-template-rows: auto auto auto;",
		"\t}",
		"\t.aside-publish-left, .aside-publish-sidebar {",
		"\t\tmin-height: auto;",
		"\t\tborder: 0;",
		"\t\tborder-bottom: 1px solid var(--aside-shell-line);",
		"\t}",
		"\t.aside-publish-viewer-header {",
		"\t\tpadding-right: 0;",
		"\t\talign-items: stretch;",
		"\t\tflex-direction: column;",
		"\t}",
		"\t.aside-publish-account { position: static; padding: 12px 18px 0; }",
		"\t.aside-publish-frame { min-height: 62vh; }",
		"}",
		"",
	].join("\n");
}
